title: "Econometrics: A Guide" 
author: Elliott Serna
logo: _static/logo.png
description: This website presents a series of guides to econometric topics, written by Elliott Serna.

parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution

only_build_toc_files: true

repository:
  url: https://github.com/elliottserna/econometrics
  branch: main

bibtex_bibfiles:
   - _static/references.bib

html:
  baseurl: https://elliottserna.github.io/econometrics
  favicon: _static/favicon.ico
  static_path: ['_static']
  extra_css:
  - css/custom.css
  - css/color.scss

latex:
   latex_documents:
      targetname: econometrics.tex

sphinx:
  extra_extensions:
    - sphinx.ext.mathjax
    - sphinx.ext.intersphinx
  config:
    html_theme: "quantecon_book_theme"
    html_theme_options:
      authors:
        - name: "Elliott Serna"
          url: "https://elliottserna.github.io"
      repository_url: "https://github.com/elliottserna/econometrics"
      description: "This website presents a series of guides to econometric topics, written by Elliott Serna." 
      keywords: "Econometrics, Economics, Policy, Data Science" 
    mathjax3_config:
      tex:
        macros:
          "argmax": "arg\\,max"
          "argmin": "arg\\,min"
    mathjax_path: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"  # Path to MathJax
