name: econometrics
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - anaconda=2024.10
  - pip
  - pip:
      - jupyter-book==1.0.3
      - quantecon-book-theme==0.7.6
      - sphinx-tojupyter==0.3.0
      - sphinxext-rediraffe==0.2.7
      - sphinx-reredirects==0.1.4
      - sphinx-exercise==1.0.1
      - sphinx-proof==0.2.0
      - ghp-import==1.1.0
      - sphinxcontrib-youtube==1.3.0
      - sphinx-togglebutton==0.3.2
  - mamba  # Add mamba if it's not already in Binder
  - pytz
